### ISSUE TITLE
Pypi does not reflect recent improvements on Github

### ISSUE THREAD

**Issue by thorbjoernl** [jgliss/geonum#26]
The source code on Github is not the same as the most recent release on pypi (see eg. https://github.com/metno/pyaerocom/issues/1050#issuecomment-2039629724). Can you please release a new version? Specifically the new version should contain the logic from the following lines: https://github.com/jgliss/geonum/blob/34861f46cc8d0c06a5e1b0b4f69d196da281dab6/geonum/topoaccessbase.py#L223

**Comment by jgliss** [comment]
Hi @thorbjoernl, many thanks for reaching out! I will try to revise the latest updates in the next days and will make a new release (which is more than overdue). I will keep you posted.

**Comment by thorbjoernl** [comment]
Appreciate it. Thank you

**Comment by jgliss** [comment]
@thorbjoernl geonum 1.5.0 is now available via PyPI, please reach out if you run into any problems.

https://pypi.org/project/geonum/
